name: Node.js CI

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: tar -cvf build.tar .
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build.tar
  lint:
    name: lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - run: tar -xvf build.tar
      - run: yarn lint
  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - run: tar -xvf build.tar
      - run: yarn test
